### PR TITLE
Refactoring to specialised functional interfaces

### PR DESCRIPTION
**Pull request by ameyaKetkar**

### CODE REVIEW

**Comment by ameyaKetkar** [comment]
These are all the under-usages of functional interfaces the tool found and refactored .
I have manually verified each change.

**Comment by ameyaKetkar** [comment]
Hello,
Any update on this pull request? I have a more refactorings for specialisation of Optional too.

**Comment by manning** [comment]
Thanks for the contribution! Sorry, we're just slow to get around to things - and I guess like to check things ourselves too. :)

I'm merging things now!

**Comment by manning** [comment]
p.s. We do like a blank line between system and CoreNLP imports. :)

**Comment by ameyaKetkar** [comment]
Thanks a lot. 
I will configure my tool to not change the import order.

**Pull request closed without merging**
