### PR TITLE
Convert a small number of stdout / stderr calls to slf4j

### PR DESCRIPTION
**Pull request by dinoboy197**
[Based on the decision to switch over to slf4j](https://github.com/stanfordnlp/CoreNLP/issues/1#issuecomment-143598156) per @manning , I thought I would put together a small PR to test the slf4j waters with reviewers.

This uses the Logging class (created previously by another contributor) to retrieve an instance of a Logger. If that isn't desired (you'd rather see just ```Logger logger = LoggerFactory.getLogger()```, please let me know and I'll adjust.

### CODE REVIEW

**Comment by J38** [comment]
Hi, first of all thanks for the contribution!  We are actually planning on not using that Logger class and just following the standard slf4j pattern ; the pattern we're going to follow is is edu.stanford.nlp.classify.SVMLightClassifierFactory as an example.  Slowly but surely over time we will be converting everything over to this new logging method.

**Comment by dinoboy197** [comment]
> We are actually planning on not using that Logger class and just following the standard slf4j pattern referenced here: http://www.slf4j.org/manual.html ; the pattern we're going to follow is in edu.stanford.nlp.classify.SVMLightClassifierFactory as an example.

Perfect! I actually prefer that style too, but i just wasn't sure since this Logging class existed...

Let me adjust my PR.

**Comment by dinoboy197** [comment]
@J38  Ping! Just checking back in on this PR.

**Comment by J38** [comment]
Hi I'll merge this today, it looks great!  Thanks again for the help!  If you are interested in helping more we'd greatly appreciate it!  Our plan is to hold off on any more logging changes until we release 3.5.3 and finalize the logging plans.  But if you'd like to convert statements, you could convert a package at a time, and then I'll review what you did and merge it in!  Once again thanks for your help and interest in Stanford CoreNLP!

**Comment by dinoboy197** [comment]
> But if you'd like to convert statements, you could convert a package at a time, and then I'll review what you did and merge it in!

You bet - do you mean just converting ```System.out.println``` and ```System.err.println``` into corresponding slf4j statements? I'm happy to keep working on that :)

**Comment by J38** [comment]
Yes I think our first goal should be to change the System.out.println and System.err.println statements, and then eventually change everything else.  Thanks again!

**Comment by manning** [comment]
Thanks. Merged.

**Pull request closed without merging**
