### PR TITLE
Refactored ChineseStringUtils.java to remove multithreading issues

### PR DESCRIPTION
**Pull request by KellenSunderland**
Hello, I've done a refactor of the ChineseStringUtils.java to address some multithreading issues that I've run into.  My problems were pretty similar to the ones reported in #263 .  I tried to refactor the code to maintain the lazy-loading of regex patterns, but also to make everything threadsafe.   

One note of caution: I'm not an expert in Chinese Segmentation, and there didn't seem to be many unit tests covering this code, so it would be great if someone could verify that there's no behavior change here.

### CODE REVIEW

**Comment by KellenSunderland** [comment]
All new/modified code in this PR is in the public domain.

**Comment by manning** [comment]
Thanks a lot!

**Comment by manning** [comment]
p.s. It's far from clear that the lazy loading of regex in this class is really in any way useful rather than just a needless complication....

**Comment by KellenSunderland** [comment]
Thanks for the merge!  I totally agree that the lazy initialization is likely unneeded complication.  I can try and clean it up using simple static initialization if no-one objects to losing lazy loading.

**Pull request closed without merging**
