### PR TITLE
Fixed -unkWord option in RNNOptions.java

### PR DESCRIPTION
**Pull request by mschnoell**
The -unkWord option is usable now ;-)

### CODE REVIEW

**Comment by AngledLuffa** [comment]
Oops, how embarrassing.  Thanks for reporting that!

We really should have an arg parsing library (ideally one which can handle
enums)

**Comment by gangeli** [comment]
Technically, we do have an arg parsing library (http://nlp.stanford.edu/nlp/javadoc/javanlp/), and it even handles Enums. I'm just bad at advertising it...

**Comment by AngledLuffa** [comment]
What's it called?  It doesn't show up on that page, at least not if you
search for "arg"

**Comment by gangeli** [comment]
Ack, I forgot Javadoc has iframes: http://nlp.stanford.edu/nlp/javadoc/javanlp-3.6.0/edu/stanford/nlp/util/Execution.html. The OpenIE code uses it, for example: https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/naturalli/OpenIE.java#L99

**Pull request merged**
